project_id: "alexfosterinvisible/Cortex-Code"
artifacts_dir: "./artifacts"
source_root: "./adw"
ports:
  backend_start: 9100
  frontend_start: 9200
agent:
  timeout_seconds: 300    # 5 minutes - prevents indefinite hangs
  max_retries: 3          # Number of retry attempts on failure
  retry_delays: [1, 3, 5] # Seconds between retries (exponential backoff)
commands:
  - "./commands"
